### PR TITLE
D1a UI

### LINKED ISSUE #155: Web App: UI for D1a

### PR DESCRIPTION
**Pull request by smiththay**
fixes #155

### CODE REVIEW

**Review by Oddvocado — CHANGES_REQUESTED** [review]
Looking good! Ran into a few issues that will need to be addressed. 

- [ ] Question 8 "PREDOMSYN" is missing. I didn't find it in the model nor did I see it in the API. Not sure if it was intentionally omitted but I wanted to point this out.
image
image

- [ ] The subcounters in section 3 are incremented incorrectly
image

- [ ] Section 1 question 2 has formatting issues
image
image

- [ ] Ran into an issue with question 2 "NORMCOG" enabling question 3 "DEMENTED".  When NORMCOG has a value of 0, DEMENTED is not always being enabled. Also had trouble saving the value of DEMENTED when marking the form as complete.
image

**Comment by smiththay** [comment]
@Oddvocado Thanks for those catches, ready for another review

**Review by Oddvocado — CHANGES_REQUESTED** [review]
Looks good! Did notice one issue though. I was able to save the form as complete while selecting more than one diagnosis as primary
tempsnip

**Comment by smiththay** [comment]
@Oddvocado good catch, ready for another review. 

There is an issue that will have a separate card for. Checkboxes that are enabled/disabled by a radio button doesn't save initially if validation on the form kicks on but will save if reentered.

**Comment by Oddvocado** [comment]
@smiththay Looks good! Only thing I noticed was this curly bracket hanging out at the bottom of the form. Other than that looks like it is ready to merge!

image

**Pull request merged**
