### PR TITLE
Form Mode, Remote Reason, Remote Modality

### LINKED ISSUE #167: UI for new base form properties like mode
Documentation for `I` packet kind:

Form mode `MODE`

- A1 - 1, In-person|2, Remote
- A1A - 1, In-person|2, Remote
- A2 - 1, In-person|2, Remote|3, Not completed
- A3 - 1, In-person|2, Remote
- A4 - 1, In-person|2, Remote|3, Not completed
- A4A - 1, In-person|2, Remote|3, Not completed
- A5D2 - 1, In-person|2, Remote
- B1 - 1, In-person|3, Not completed
- B3 - 1, In-person|3, Not completed
- B4 - 1, In-person|2, Remote
- B5 - 1, In-person|2, Remote|3, Not completed
- B6 - 1, In-person|2, Remote|3, Not completed
- B7 - 1, In-person|2, Remote|3, Not completed
- B8 - 1, In-person|2, Remote
- B9 - 1, In-person|2, Remote
- C2 - 1, In-person|2, Remote (video)
- C2T - 2, Remote (telephone)
- D1A - 1, In-person|2, Remote
- D1B - 1, In-person|2, Remote

Not included reason codes `NOT`

- A1 - required
- A1A - required
- A2 - 94, No co-participant|95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- A3 - required
- A4 - 95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- A4A - 95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- A5D2 - required
- B1 - 94, Remote visit|95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- B3 - 94, Remote visit|95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- B4 - required
- B5 - 95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- B6 - 95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- B7 - 95, Physical problem|96, Cognitive/behavioral problem|97, Other|98, Verbal refusal
- B8 - required
- B9 - required
- C2 - required when in-person or remote and video
- C2T - required when remote and telephone
- D1A - required
- D1B - required

Remote reason codes `RMMODE`

- Most forms - 1, In-person|2, Remote 
- B1 - remote not allowed
- B3 - remote not allowed
- C2 - 2, Video
- C2T - 1, Telephone

### PR DESCRIPTION
**Pull request by ashleybot**
Fixes #167

Custom tag helper for disabling options not allowed for certain forms

Screenshot 2024-06-27 at 3 40 43 PM

Example of REQUIRED form allowing remote
Screenshot 2024-06-28 at 3 22 00 PM

Example of optional form NOT allowing remote
Screenshot 2024-06-28 at 3 22 53 PM

Example of optional form allowing remote
Screenshot 2024-06-28 at 3 23 46 PM

This PR should

- [ ] Follow all form requirements outlined in UDSv4 documentation for whether a form is required or optional, or allows remote
- [ ] Adjusts allowed not completed reason codes according to UDSv4 documentation
- [ ] Adjusts allowed remote reason codes according to UDSv4 documentation
- [ ] Adjust form saving states to the In-progress or Finalized now that FormMode indicates whether the for is not included (`NotComplete`)
- [ ] Initials are required and the [UX will be improved in a separate effort to autofill ](https://github.com/UK-SBCoA/uniform-data-set-dotnet-web/issues/173)

### CODE REVIEW

**Comment by mlan225** [comment]
Running into an interesting issue when creating a visit. Running Api and Web PR branches and have run migrations on my local API database so things should be up to date on my end.

Can you confirm if the packet select options below are the intended options?

image

Also getting an error after attempting the creation of the visit above

image

**Comment by mlan225** [comment]
B6 should allow in-person | remote | not completed but allows no options

**Comment by mlan225** [comment]
I was able to test the rest of the forms successfully, except for the C2 and C2T, after editing the required forms to be finalized, the F packet did not have those forms available.

The rest looks good though! The rest of it functions as promised after the B6 options are fixed ✅

**Comment by mlan225** [comment]
A literal non issue, but just mentioning it here so we know about it, but the styling for the applied validation messages when it is checked manually with an in progress status appear different than the ones checked against the model with intrusive validation

in progress error:
image

Finalized error:
image

**Comment by mlan225** [comment]
> @mlan225 Fixed B6. Handing this to @smiththay for a second pass since it has such a large affect-area.

sounds good 👍

**Comment by smiththay** [comment]
@ashleybot after a second pass through, everything looks and functions as it should! I was not able to test C2/C2T. The issue I thought I found was a mistake on my part. Ready to go!

**Review by smiththay — APPROVED** [review]
@ashleybot after a second pass through, everything looks and functions as it should! I was not able to test C2/C2T. The issue I thought I found was a mistake on my part. Ready to go!

**Pull request merged**
