### PR TITLE
Create a5 d2 UI

### PR DESCRIPTION
**Pull request by mlan225**
Resolves: #133 

- [x] Create form Ui by adding questions, labels, formatting, and other text
- [x] Make sure the save functionality works for complete, partial save, etc.
- [x] Add behaviors for enable/disable
- [x] Add simple validation to the model
- [x] Add any complex validation that may be required
- [x] Review the form Ui to clean up any issues with the front end (run spell check, double check element structure, etc.)
- [x] Apply edits made to the a5d2 NACC repo
- [x] Add custom validation that we talked about for C2

### CODE REVIEW

**Comment by mlan225** [comment]
All questions have been added to the form. 

Next, I will be making sure the backend functions such as saving and editing work before moving on to cleaning up the front-end Ui

**Comment by mlan225** [comment]
@ashleybot One more variable that may need a text adjustment. Posting up the evidence
`OTHERCOND` in the documentation 
`OTHCOND` in the API

NACC documentation
image

API model
image

**Comment by mlan225** [comment]
Similar to the A1a, I made the A5D2 is available on IVP and TIP visits

**Comment by mlan225** [comment]
uh.. huh? lol 

image

**Comment by mlan225** [comment]
Im going to convert back to draft and move out of review until we can take a look at this linter error

**Comment by mlan225** [comment]
Went in a a bit of a rabbit hole and couldn't get the `.gitleaksignore` file to ignore the fingerprint of the error: https://github.com/gitleaks/gitleaks?tab=readme-ov-file#gitleaksignore

Undid any changes to the PR related to testing this

**Comment by mlan225** [comment]
@ashleybot Ready for review

Not super sure what we should do about the gitleaks error yet, I wasn't able to get the ignore settings file to work for the action run. I'd assume this error will persist into main if we don't do anything about it here but I also don't want it to hold up a review of the form itself in the meantime. 

Review checklist:
- [ ] A5D2 form has been added
- [ ] A5D2 can be partially saved / completely saved
- [ ] A5D2 validation functions correctly
- [ ] A5D2 client-side validation behaviors enable and disable fields successfully
- [ ] Text labels, section headers, and instruction text match the NACC documentation
- [ ] Modification to table cell tag helper does not break existing functionality

**Comment by mlan225** [comment]
Will update the release version after the review process

**Comment by smiththay** [comment]
Marvin and I paired and removed Tailwind dark theme class modifier. Continuing the review.

**Comment by smiththay** [comment]
Hey @mlan225, noticed a few behavior items not functioning correctly. 

1.) For question 4g. the checkboxes in 4g3. and question 4g4. do not get disabled when 4g. is Unknown
Screenshot 2024-04-08 at 4 53 56 PM



2.) Similar situation is happening here for question 5f. where checkboxes are not disabled if 5f. is absent or unknown.
Screenshot 2024-04-08 at 3 43 03 PM



3.) For questions 5m. the checkboxes are disabled but 5m11. remains enabled. 
Screenshot 2024-04-08 at 3 47 56 PM
Screenshot 2024-04-08 at 3 48 19 PM


4.)For the checkboxes that are disabled, they visually appear enabled like in question 5a. This can be resolved by adding `disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none` to the checkboxes class.
Screenshot 2024-04-08 at 3 41 22 PM

**Comment by mlan225** [comment]
Resolved the PR review comments and fixed some minor issues with the subcounters with sub-sections

**Comment by smiththay** [comment]
@mlan225 This form looks great, especially with how massive and involved it it. There are just a few more small items I discovered on the additional review.
&nbsp;
&nbsp;
1.) **CANCOTHERX** does not have parameters for Maxlength and it is throwing error.
Screenshot 2024-04-22 at 3 01 21 PM
Screenshot 2024-04-22 at 3 01 56 PM
&nbsp;
&nbsp;
2.) **CANCERAGE** does not have any validation so I can save the form without input
Screenshot 2024-04-22 at 3 05 36 PM
Screenshot 2024-04-22 at 3 02 42 PM
&nbsp;
&nbsp;
3.) **HIVAGE** has a range of 0-2 or 9 currently but the docs state 0-110, 999
Screenshot 2024-04-22 at 3 04 19 PM
Screenshot 2024-04-22 at 3 03 32 PM

**Comment by mlan225** [comment]
Good catches @smiththay ! I made the adjustments to fix those comments and updated the PR branch with main

### Fixes
1. Max length parameters added to CANCOTHERX annotation to fix bug
2. CANCERAGE is required if the parent item for the section is 1 or 2
3. HIVAGE attribute range adjusted to match documentation

**Review by smiththay — APPROVED** [review]
@mlan225 issues are resolved and looks great!

**Pull request merged**
