### PR TITLE
D1b UI

### LINKED ISSUE #156: Web App: UI for D1b
- [ ] Define the D1b model with all necessary properties
 - [ ] Update all mappers and form fields
 - [ ] Validate fields with Regex, range, custom validation, etc.
 - [ ] Add form to form contract
 - [ ] Update D1b UI to match NACC documentation.
 - [ ] Modify enable/disable behavior and implement on UI
 - [ ] Insure form matches NACC documentation with correct UI, logic, validation, behavior and ensure data is saving correctly 

View Docs: [https://github.com/naccdata/uniform-data-set/tree/main/forms/uds/d1b](https://github.com/naccdata/uniform-data-set/tree/main/forms/uds/d1b)

### PR DESCRIPTION
**Pull request by smiththay**
fixes #156

### CODE REVIEW

**Comment by smiththay** [comment]
@mlan225 good catches! Fixed everything but just wanted some clarity on the first point (Paragraph text under question may want to be included).

**Comment by mlan225** [comment]
> @mlan225 good catches! Fixed everything but just wanted some clarity on the first point (Paragraph text under question may want to be included).

not even gonna lie to ya... I have no idea what I meant by that lol, but I'm not noticing anything it could have meant anymore, so 🤷‍♂️

**Comment by mlan225** [comment]
@smiththay  Getting an interesting interaction with the form not saving the value for 7a, the value is being saved to the database, but the form loads up with no inputs selected. Can you check this on your end and see if its just happening to me?

**Comment by smiththay** [comment]
@mlan225 Thanks for the catch. I was able to replicate the issue. I fixed the behavior but unraveled a slew of other behavior issues but should now be in working order and ready for review.

**Comment by mlan225** [comment]
@smiththay  Looks like those previous things were fixed up 👍 , something new I've noticed though is that `CSFOTHX` is not required when CSFOTH is 1, is this intentional? 

image

**Comment by mlan225** [comment]
@smiththay noticed a small text issue in the error message for question 1 and just wanted to verify some functionality for the checkbox section starting at question 12 to the end of the form

- [ ] Question 1 error message: "The Were any biomarker results used to support the current etiological diagnosis? field is required."
- [ ] Looks like 14c radio option is not required when 14 is present, should it be? 14c question text says: "if FTLD (QUESTION 14) is present, specify FTLD subtype)
- [ ] It also looks like questions 12 to the end, the checkboxes don’t' require a radio button to be selected, is this intentional?

For extra context on the last 2 points, I am able to submit this as a complete form. Selecting a radio option for 14a yields the same result:
image

**Comment by smiththay** [comment]
@mlan225 thanks again, I updated the message for Q1 and validation for Q14c. In regards to the radio buttons for Q12 and onward, they are not required.
Screenshot 2024-06-06 at 3 39 52 PM

**Comment by mlan225** [comment]
Smith is tackling the required tags for questions 8 and 11

**Comment by mlan225** [comment]
Looks good @smiththay  ✅, I have no more nothings to say lol

**Comment by smiththay** [comment]
@mlan225 Thanks for having exceptional eyes!

**Pull request merged**
