### PR TITLE
A4a UI

### LINKED ISSUE #134: Web App: UI for A4a
- [ ] Define the A4a model with all necessary properties
 - [ ] Update all mappers and form fields
 - [ ] Validate fields with Regex, range, custom validation, etc.
 - [ ] Add form to form contract
 - [ ] Update A4a UI to match NACC documentation.
 - [ ] Modify enable/disable behavior and implement on UI
 - [ ] Insure form matches NACC documentation with correct UI, logic, validation, behavior and ensure data is saving correctly 

View Docs: [https://github.com/naccdata/uniform-data-set/tree/main/forms/uds/a4a](https://github.com/naccdata/uniform-data-set/tree/main/forms/uds/a4a)

### PR DESCRIPTION
**Pull request by smiththay**
fixes #134

### CODE REVIEW

**Comment by smiththay** [comment]
Screenshot 2024-04-05 at 1 45 12 PM
Question 1 will activate all entries in the table for clinical treatments and/or trials. NACC docs don't show a way to enable specific number of rows. This functionality will remain as it is currently implemented until further testing by clients is conducted.

**Comment by mlan225** [comment]
Looks good, but there were 2 things that we already talked about earlier. I'll throw them on here for records sake:

1. I asked if we'll need some additional for the table questions. It seems you have some good direction to move forward with that
2. Looks like the instruction text was updated a couple of days ago, lol not much we can do about keeping this up to date especially while in PR review or post review until we figure out a system for checking in on these. But while we are here, might as well updated it 🤷

**Comment by smiththay** [comment]
@mlan225 Ready for another review.

**Comment by mlan225** [comment]
Heyo @smiththay, validation looks great! I did notice one small thing with the checks for last 2 columns. 

Looks like the second to last column in the tables only check for the second option radio option "clinical trial" and ignores option 3 "clinical care and clinical trial" for a valid check. Is this intentional?
image

The rules in the documentation for the question in the screenshot states: 
> If CARETRIAL3 is 2 or 3 then TRIALGRP3 cannot be blank

**Comment by smiththay** [comment]
@mlan225 thanks, that was an oversight on my part and has been addressed and ready for another look through

**Comment by mlan225** [comment]
Awesome, Looks good to me ✔️

**Pull request merged**
